AWSTemplateFormatVersion  :  '2010-09-09'
Description               :  'This template creates the ECS cluster'

Parameters: 
  VPC:
    Description: Choose which VPC this ECS cluster should be deployed to
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to use for the ECS instances
    Type: AWS::EC2::SecurityGroup::Id
           
  InstanceType:
    Description: The ECS EC2 instance type
    Type: String
    Default: t2.small
    ConstraintDescription: must be a valid EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
  MinSize:
    Description: The minimum number of ECS nodes
    Type: Number
    Default: 2

  MaxSize:
    Description: The maximum number of ECS nodes
    Type: Number
    Default: 2 
        
Mappings:
  AWSRegionToAMI:
      us-east-1 :
          AMI : ami-28456852
      us-east-2 :
          AMI : ami-ce1c36ab
      us-west-2 :
          AMI: ami-decc7fa6
      us-west-1 :
          AMI : ami-74262414  

Resources:
  
#  Subnets:
#    -  Fn::ImportValue:
#            kiran-test-yml-PublicSubnetID1
#
#    -  Fn::ImportValue:
#            kiran-test-yml-PublicSubnetID2 

#  SecurityGroupIds:
#  - Fn::ImportValue:
#        kiran-test-yml-sg
#    
#  ECSCluster:
#    Type: AWS::ECS::Cluster
  
#  LaunchConfiguration:
#    Type: AWS::AutoScaling::LaunchConfiguration
#    Properties:
#        ImageId:  !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
#        InstanceType: !Ref InstanceType
#        SecurityGroupIds:   
#        - Fn::ImportValue:
#            !Sub "$kiran-test-yml-sg"
#            
#
#        
#  AutoScalingGroup:
#    Type: AWS::AutoScaling::AutoScalingGroup
#    Properties:
#      VPCZoneIdentifier: 
#      -  Fn::ImportValue: !Sub "$kiran-test-yml-PublicSubnetID1"
#
#      -  Fn::ImportValue: !Sub "$kiran-test-yml-PublicSubnetID2 "
#      LaunchConfigurationName: !Ref LaunchConfiguration
#      MinSize: !Ref MinSize
#      MaxSize: !Ref MaxSize
#      Cooldown: 60         

    ECSCluster:
        Type: AWS::ECS::Cluster

    LaunchConfiguration:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            ImageId:  !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
            InstanceType: !Ref InstanceType
            SecurityGroups:  
             - !Ref SecurityGroup 
                                
    AutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier: !Ref Subnets           
            LaunchConfigurationName: !Ref LaunchConfiguration
            MinSize: !Ref MinSize
            MaxSize: !Ref MaxSize
            Cooldown: 60         

 